spring:
  application:
    name: atm
  datasource:
    url: jdbc:h2:mem:atmdb
    username: h2
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB        # increase if necessary
      max-request-size: 10MB     # increase if necessary


